spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:dentifier.sqlite
  jpa:
    database-platform: com.ztesoft.config.compare.config.SQLiteDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  #  热更新
  devtools:
    livereload:
      enabled: true
  resources:
    static-locations: classpath:/static/

# 应用部署环境，win：则会自动转换文件路径为windows路径
#  （由于unix环境文件分隔符与windows环境不一致，取文件的服务器为linux，本地测试环境为windows，需要转换文件路径）
#  ，设置为其他值则不作转换，部署到生产环境需要修改此变量为win以外的值
sysInfo: unix
#sysInfo: win

logging:
  path: classpath:/
  file: server.log
  level:
    root: info
